#### Homework Code

In [2]:
import numpy as np

In [24]:
a = np.matrix([[5, 6], [3, 7]])
b = np.matrix([[3,2], [1,5]])

Matrix Multiplication

In [25]:
a*b

matrix([[21, 40],
        [16, 41]])

In [4]:
b*a

matrix([[21, 32],
        [20, 41]])

Matrix Addition

In [9]:
2*a

matrix([[10, 12],
        [ 6, 14]])

In [10]:
0.5*b

matrix([[ 1.5,  1. ],
        [ 0.5,  2.5]])

In [11]:
a + b

matrix([[ 8,  8],
        [ 4, 12]])

In [12]:
a -b

matrix([[2, 4],
        [2, 2]])

Quadratic Form a(t)* B * a

In [13]:
a = np.matrix([[2],[3]])

In [14]:
B = np.matrix([[1,2],[3,1]])

In [15]:
np.dot(a.T,B)*a

matrix([[43]])

Calculate Determinant which is also product of its eigen values

In [14]:
A = np.matrix([[1,3,2,1],[4,0,5,0],[2,7,1,6],[0,1,4,10]])
A

matrix([[ 1,  3,  2,  1],
        [ 4,  0,  5,  0],
        [ 2,  7,  1,  6],
        [ 0,  1,  4, 10]])

In [15]:
round(np.linalg.det(A))


542.0

In [16]:
a , b =np.linalg.eig(A)
np.prod(np.array(a))

542.00000000000057

Calculate Inverse

In [18]:
A = np.matrix([[1,2,4],[1,3,7],[1,-1,-2]])

In [19]:
A

matrix([[ 1,  2,  4],
        [ 1,  3,  7],
        [ 1, -1, -2]])

In [20]:
np.linalg.inv(A)

matrix([[ 0.33333333,  0.        ,  0.66666667],
        [ 3.        , -2.        , -1.        ],
        [-1.33333333,  1.        ,  0.33333333]])

In [21]:
A = np.matrix([[3,8,1],[0,4,3],[0,3,4]])
A

matrix([[3, 8, 1],
        [0, 4, 3],
        [0, 3, 4]])

In [22]:
np.linalg.eig(A)

(array([ 3.,  7.,  1.]), matrix([[ 1.        ,  0.84664878,  0.92717265],
         [ 0.        ,  0.37628835, -0.26490647],
         [ 0.        ,  0.37628835,  0.26490647]]))